# Generated by Django 3.0.7 on 2020-06-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avtar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
