# Generated by Django 3.0.7 on 2020-06-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_avtar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
