# Generated by Django 3.0.7 on 2020-07-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articlepost_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='links',
            new_name='likes',
        ),
    ]
